services:
  nginx:
    image: nginx:latest
    ports:
      - "1080:1080"
    restart: always
    depends_on:
      - gotenberg
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000"
    restart: always
    environment:
      TZ: America/Sao_Paulo
    command:
      - "gotenberg"
      - "--webhook-disable"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 150M
      mode: replicated
      replicas: 2
